kijayjay/items/urls.py
# -*- coding: utf-8 -*-
"""
Created on Tue May 11 14:29:23 2021

@author: keren
"""

from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views
from user import views as user_views

app_name='items'

#Urls to each of my item related views
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('sell_item', views.itemSell_view, name='sell_item' ),
    path('item/<int:pk>/', views.GetItemDetail.as_view(),name='item_details'),
    path('item/like/<int:pk>/', views.LikeView.as_view(), name='like_items'),
    path('items_liked/', views.LikedItemsView.as_view(), name='liked_items'),
    path('my_items/', views.MyItemsView.as_view(), name='my_items'),
    path('item/buy_item/<int:pk>/', views.BuyItemView.as_view(), name='buy_item'),
    path('item/delete/<int:pk>/', views.ItemDeleteView.as_view(),name='item_delete'),
    path('user/<int:pk>/', user_views.ProfileView.as_view(), name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kijayjay/kijayjay/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from user import views as iview

urlpatterns = [
    path('', include('items.urls')),
    path('', include('user.urls')),
   #path('login/', iview.login_view, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name ='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name ='user/logout.html'), name='logout'),
    path('admin/', admin.site.urls),

]

kijayjay/user/urls.py
from django.urls import path

from . import views
from items import views as iview
from django.contrib.auth import views as auth_views

app_name='user'

#My urls to each of my views
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name ='user/login.html'), name='login'),
    path('', iview.IndexView.as_view(), name='index'),
    path('user/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('user/update/<int:pk>/', views.update_profile, name='update_profile'),
]

kijayjay/items/models.py
from django.urls import reverse
from django.utils import timezone
import datetime

#No models are declared here, all of the site's models are declared in the postgresql_db models.py

kijayjay/items/forms.py
# -*- coding: utf-8 -*-
"""
Created on Tue May 18 16:43:15 2021

@author: keren
"""

from django import forms

from postgresql_db.models import Item

#Form to add an item to sell, it contains all details about the item
class SellItemForm(forms.ModelForm):
    price = forms.DecimalField(max_digits=10, decimal_places=2, label_suffix=(' ($)'))
    class Meta:
        model = Item
        fields = [
            'title',
            'description',
            'price',
            'images'
            ]

#Form to add an item to sell, it contains all details about the item
class BoughtItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'title',
            'description',
            'price',
            'images'
            ]

kijayjay/items/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from postgresql_db.models import Item, Like, Profile
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from .forms import SellItemForm, BoughtItemForm
from django.contrib.auth.decorators import login_required
from urllib.parse import urlencode
from django.contrib import messages

#IndexView is the homepage for the Kijayjay site
class IndexView(generic.ListView):
        template_name = 'items/index.html'
        paginate_by = 5
        model = Item
        ordering = ('-pk')     
        #Return filtered items depending of select search query.
        def get_queryset(self):
            query = self.request.GET.get('search')
            filter_by = self.request.GET.get('filter_by')
            sort_by = self.request.GET.get('sort_by')
            page = self.request.GET.get('page')
            if query:
                if filter_by=='title':
                    if 'ASC' in sort_by:
                        object_list = Item.objects.filter(title__icontains=query).order_by(sort_by.replace('ASC',''))
                    elif 'DESC' in sort_by:
                        object_list = Item.objects.filter(title__icontains=query).order_by('-'+sort_by.replace('DESC',''))
                elif filter_by=='price':
                    if 'ASC' in sort_by:
                        object_list = Item.objects.filter(price__icontains=query).order_by(sort_by.replace('ASC',''))
                    elif 'DESC' in sort_by:
                            object_list = Item.objects.filter(price__icontains=query).order_by('-'+sort_by.replace('DESC',''))
                return object_list
            else:
                return Item.objects.all()
        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            gt = self.request.GET.copy()
            if 'page' in gt:
                del gt['page']
            context['params'] = urlencode(gt)
            context['title'] = 'Items Listed'
            return context



#View for the user to add the item it desires to sell   
@login_required
def itemSell_view(request):
    if request.method == 'POST':
        form = SellItemForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit = False)
            obj.user = request.user;
            obj.save()
            form.save()
            return redirect('items:index')
    else:
        form = SellItemForm()    
    return render(request, 'items/sell_item.html', {'form':form})

#It allows the user to view details of item from the homepage
class GetItemDetail(LoginRequiredMixin,generic.DetailView):
    template_name = 'items/item_details.html'
    model = Item
    extra_context = {'title':'Item details'}
    #permission_required = 'items.view_items'
    
#It allows the user to view details of item from the homepage
class BuyItemView(LoginRequiredMixin, generic.DetailView):
    '''template_name = 'items/buy_item.html'
    model = Item
    fields = ['title','description', 'images', 'price', 'location']
    permission_required = 'items.view_items' '''
    def post(self, request, *args, **kwargs):
        profile = Profile.objects.filter(user =request.user).get()
        item_bought = get_object_or_404(Item,id=request.POST.get('item_id'))
        
        if (profile.money_available < item_bought.price):
             messages.success(request,'Insufficient money')
             return render(request, 'items/index.html')
        else:
            profile.money_available = profile.money_available - item_bought.price
            profile.save()
            seller_profile =  Profile.objects.filter(user = item_bought.user).get()
            seller_profile.money_available = seller_profile.money_available + item_bought.price
            seller_profile.save()
            item_bought.delete()
            return redirect('items:profile')

#View that allows registered users to like an item
class LikeView(LoginRequiredMixin, generic.View):
    #Stores the user's like to the database for the item they liked.
    def post(self, request, *args, **kwargs):
        like = Like ()
        like.item = get_object_or_404(Item, id=request.POST.get('item_id'))
        profile = Profile.objects.filter(user =request.user).get()
        item =  get_object_or_404(Item, id=request.POST.get('item_id'))
        item.likes = item.likes + 1
        item.save()
        like.user =  User.objects.filter(id= profile.user.id).get()
        like.save()
        return redirect('items:index')
    
@login_required
def boughtItem_view(request):
    if request.method == 'POST':
        form = BoughtItemForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit = False)
            obj.user = request.user;
            obj.save()
            form.save()
            return redirect('items:index')
    else:
        form = ()    
    return render(request, 'items/sell_item.html', {'form':form})

#View to delete an item
class ItemDeleteView(LoginRequiredMixin,generic.DeleteView):
    model = Item
    def post(self, request, *args, **kwargs):
        todelete = Item ()
        todelete.item = get_object_or_404(Item, id=request.POST.get('item_id'))
        todelete.delete()
        return redirect('items:index')
    
#Displays the items that an user liked.
class LikedItemsView(generic.ListView):
    template_name = 'items/liked_items.html'
    paginate_by = 8
    model = Like
    extra_context = {'title':'Liked Items'}
    ordering = ('-pk')
    #Retrieves all the items the user liked.
    def get_queryset(self):
        user_obj= User.objects.filter(id=self.request.user.id).get()
        object_list = Like.objects.filter(user=user_obj) 
        return object_list

# The view that lets a registered user edit their posted for sell item.
class ItemEditView(LoginRequiredMixin,PermissionRequiredMixin, generic.UpdateView):
    model = Item
    fields = ['title','description', 'images', 'price', 'location']
    extra_context = {'edit':'Edit item'}
    permission_required = 'postgresql_db.change_items'
    success_url = reverse_lazy('index')

class MyItemsView(generic.ListView):
    template_name = 'items/my_items.html'
    paginate_by = 5
    model = Item
    ordering = ('-pk') 
    def get_queryset(self):
         user_items= Item.objects.filter(user_id=self.request.user.id)
         return user_items

kijayjay/items/templates/items/base.html
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'items/style_index.css' %}">
<div class = "header"> <h1>Kijayjay</h1></div>

<ul class = "menu_items">
  <li class="item"><a class="mylink" href="{% url 'items:index' %}">Home</a></li>
  <li class="item"><a class="mylink" href="{% url 'items:sell_item' %}">Sell</a></li>
  {%if user.is_authenticated %}
  <li class="item" style="float:right"><a class="mylink" href="{% url 'logout' %}">Log out</a></li>
  <li class="item"><a class="mylink" href="{% url 'user:profile' user.profile.id %}">Profile</a></li>
  <li class="item"><a class="mylink" href="{% url 'items:liked_items' %}">Liked items</a></li>
  <li class="item"><a class="mylink" href="{% url 'items:my_items' %}">My items</a></li>
  {%if user.profile.picture%}
   <img class="rounded-circle"  src="{{user.profile.picture.url}}" width="50" height="50">
  {%endif%}

  {% else %}
  <li class="item" style="float:right"><a class="mylink" href="{% url 'login' %}">Login</a></li>
  <li class="item" style="float:right"><a class="mylink" href="{% url 'user:signup' %}">Register</a></li>
  {%endif%}
  
</ul> 

<div id='main-container'>
    <section id='middle_div'>
      {% block content %}

      {% endblock content %}
    </section>
  </div>
<footer>Created by: Keren Rivera Pérez</footer>
</html>

kijayjay/items/templates/items/buy_item.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'items/style_index.css' %}">
<div class = "header"> <h1>Kijayjay</h1></div>

<ul class = "menu_items">
  <li class="item"><a class="mylink" href="{% url 'items:index' %}">Home</a></li>
  <li class="item"><a class="mylink" href="{% url 'items:sell_item' %}">Sell</a></li>
  {%if user.is_authenticated %}
  <li class="item" style="float:right"><a class="mylink" href="{% url 'logout' %}">Log out</a></li>
  <li class="item" style="float:right">
  <form>
       <input class="item" type="text" style="float:right" placeholder="Search..">
       <button class="item" style="float:right" >Search</button>
   </form>
   </li>
  {% else %}
  <li class="item" style="float:right"><a class="active2" href="{% url 'login' %}">Login</a></li>
  {%endif%}
  
</ul> 
 
<h2>Are you sure you want to buy this item?<h2>
{% block content %}
<section id='item_details'>
<form  action= "buy_items" method="POST">
  {% csrf_token %}
  <h3><b>{{ item.title }}</b></h3>
        <h4><b>Description:</b> {{ object.description }}</h4> 
        <h4><b>Price:</b> {{ object.price }}</h4>
        <h4><b>Location:</b> {{ object.location }}</h4>
  <button type="submit" name="item_id" value="{{ object.id }}" class="btn btn-primary btn-sm">Buy</button>

{% endblock content %}

kijayjay/items/templates/items/index.html
{% extends './base.html' %}

{% block content %}
<h2>Items for sell</h2> 
{% csrf_token %}
<div class='search'>
      <form action="{% url 'items:index' %}" method='GET'>
        <section class="sort">
         <input type="search" placeholder="Enter keyword or number" name="search" />
          <label>Filter by:</label>
          <select name='filter_by'>
            <option value="title">Title</option>
            <option value="price">Price</option>
          </select>
          <label>Sort by:</label>
          <select name='sort_by'>
            <option value="titleASC">Title ASC</option>
            <option value="titleDESC">Title DESC</option>
            <option value="priceASC">Price ASC</option>
            <option value="priceDESC">Price DESC</option>
          </select>

          <button type="submit" name="button" class="btt_link" id="search_button">Search</button>
        </section>
      </form>
    </div>

{% if object_list %}
<ul>
{% for item in object_list %}
<li><a href="{% url 'items:item_details' item.id %}">{{ item.title }} {{ item.price }} $</a></li>
{% endfor %}
</ul>

<div class="pagination">
<section class="sort">
    {% if page_obj.has_previous %}
    <button type="button" name="button"><a class="button_link" href="?page=1&{{params}}">« First</a></button>
    <button type="button" name="button"><a class="button_link" href="?page={{ page_obj.previous_page_number }}&{{params}}">Previous</a></button>
    {% endif %}
     <p >Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}</p>
    {% if page_obj.has_next %}
    <button type="button" name="button"><a class="button_link" href="?page={{ page_obj.next_page_number }}&{{params}}">Next</a></button>
    <button type="button" name="button"><a class="button_link" href="?page=2&{{params}}">Last » </a></button>
    {% endif %}
    </section>
</div>

{% else %}
<p>No items are available.</p>
{% endif %}
{% endblock %}


<footer>Created by: Keren Rivera Pérez</footer>

kijayjay/items/templates/items/item_details.html
{% extends './base.html' %}
{% block content %}
{% block title %} <h2>{{title}} </h2>{% endblock %}

        <h3><b>{{ object.title }}</b></h3>
        <h4><b>Description:</b> {{ object.description }}</h4> 
       
        <h4><b>Price:</b> {{ object.price }}</h4>
        {%if object.images %}
        <h4><b>Images:</b> <img src="{{ object.images.url }}" width="150" height="150"></h4>
        {%endif%}
        <h4><b>Total likes:</b> {{ object.likes }}</h4>
        <h4><b>Seller:</b> {{ object.user.username }}</h4>
<section class="sort">
<form action="{% url 'items:like_items' object.id %}" method="POST">
{% csrf_token %}
  <button type="submit" name="item_id" value="{{ object.id }}" class="btn btn-primary btn-sm">Like</button>
  
</form>
<form action="{% url 'items:buy_item' object.id %}" method="POST">
{% csrf_token %}
  <button type="submit" name="item_id" value="{{ object.id }}" class="btn btn-primary btn-sm">Buy now!</button>
</form>
</section>

<form action="{% url 'items:buy_item' object.id %}" method="POST">
{% csrf_token %}
  <button type="submit" name="item_id" value="{{ object.id }}" class="btn btn-primary btn-sm">Comment</button>
</form>
{% endblock content %}

kijayjay/items/templates/items/liked_items.html
{% extends './base.html' %}
{% block content %}

{% block title %}<h2>{{title}}</h2>{% endblock %}

{% if object_list %}
<ul>
{% for item in object_list %}

<li><a href="{% url 'items:item_details' item.item.id %}">{{ item.item.title }} {{ item.item.price }} $</a></li>
{% endfor %}
</ul>

{% else %}
<p>Give some likes to fill the big empty</p>
{% endif %}

{% endblock content %}


<footer>Created by: Keren Rivera Pérez</footer>

kijayjay/items/templates/items/my_items.html
{% extends './base.html' %}
{% block content %}

{% block title %}<h2>{{title}}</h2>{% endblock %}

{% if object_list %}
<ul>
{% for item in object_list %}
<li><a href="{% url 'items:item_details' item.id %}">{{ item.title }} {{ item.price }} $</a></li>
<button type="button" name="button" style="background:red; margin-left: 10px"><a class="button_link" >Delete</a></button>
{% endfor %}
</ul>
<div class="pagination">
  <span>
    {% if page_obj.has_previous %}
    <button type="button" name="button"><a class="button_link" href="?page=1&{{params}}">« First</a></button>
    <button type="button" name="button"><a class="button_link" href="?page={{ page_obj.previous_page_number }}&{{params}}">Previous</a></button>
    {% endif %}

    <span class="current">
      <p style="font-family:emoji; font-size: 20px">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}</p>
    </span>
    {% if page_obj.has_next %}
    <button type="button" name="button"><a class="button_link" href="?page={{ page_obj.next_page_number }}&{{params}}">Next</a></button>
    <button type="button" name="button"><a class="button_link" href="?page=2&{{params}}">Last » </a></button>
    {% endif %}
</div>
{% else %}
<p>Sell some items to fill the big empty</p>
{% endif %}

{% endblock content %}


<footer>Created by: Keren Rivera Pérez</footer>

kijayjay/items/templates/items/sell_item.html
{% extends './base.html' %}

{% block content %}
<h2>Sell item<h2>
<form action= "sell_item" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <p>
    {{ field.label_tag}} <br>
    {{ field }}</p>
    {% endfor%}
    
    <button type="submit">Post</button>
</form>
{% endblock content%}