kijayjay/items/urls.py
# -*- coding: utf-8 -*-
"""
Created on Tue May 11 14:29:23 2021

@author: keren
"""

from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views
from user import views as user_views

app_name='items'

#Urls to each of my item related views
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('sell_item', views.itemSell_view, name='sell_item' ),
    path('item/<int:pk>/', views.GetItemDetail.as_view(),name='item_details'),
    path('item/like/<int:pk>/', views.LikeView.as_view(), name='like_items'),
    path('items_liked/', views.LikedItemsView.as_view(), name='liked_items'),
    path('my_items/', views.MyItemsView.as_view(), name='my_items'),
    path('item/buy_item/<int:pk>/', views.BuyItemView.as_view(), name='buy_item'),
    path('item/delete/<int:pk>/', views.ItemDeleteView.as_view(),name='item_delete'),
    path('user/<int:pk>/', user_views.ProfileView.as_view(), name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kijayjay/kijayjay/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from user import views as iview

urlpatterns = [
    path('', include('items.urls')),
    path('', include('user.urls')),
   #path('login/', iview.login_view, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name ='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name ='user/logout.html'), name='logout'),
    path('admin/', admin.site.urls),

]

kijayjay/user/urls.py
from django.urls import path

from . import views
from items import views as iview
from django.contrib.auth import views as auth_views

app_name='user'

#My urls to each of my views
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name ='user/login.html'), name='login'),
    path('', iview.IndexView.as_view(), name='index'),
    path('user/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('user/update/<int:pk>/', views.update_profile, name='update_profile'),
]

kijayjay/user/models.py
from django.db import models

#Models are in the postgresql_db models.py

kijayjay/user/forms.py
# -*- coding: utf-8 -*-
"""
Created on Wed May 12 17:51:58 2021

@author: keren
"""
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from postgresql_db.models import Profile

#The sign up form is created using as a base some of the fields from the User Model and the Profile model
#So it uses both UserForm and ProfileForm (for those extra fields)
class UserForm(forms.ModelForm):
    first_name = forms.CharField(label='First name:', max_length=30, required=True, help_text='Required')
    last_name = forms.CharField(label='Last name',max_length=30, required=True, help_text='Required')
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password')
    def save(self, commit=True):
    # Save the provided password in hashed format
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

#Form for profile data
#This form has a name field and picture field.
class ProfileForm(forms.ModelForm):
    birth_date = forms.DateField(label='Date of birth:', help_text='Enter a date with any of the following formats: Y-m-d, m/d/y'
                                 , widget=forms.widgets.DateTimeInput)
    class Meta:
        model = Profile
        fields = ('picture', 'birth_date')
        
# This form has a username field and an picture field.
class ProfileUpdateForm(UserChangeForm):
    birth_date = forms.DateField(label='Date of birth:', help_text='Enter a date with any of the following formats: Y-m-d, m/d/y'
                                 , widget=forms.widgets.DateTimeInput, required=False)
    email = forms.EmailField(label='Email:', max_length=254,required=False, help_text='Enter a valid email address')
    username = forms.CharField(label='Username', max_length=70, required=False)
    password = forms.CharField(widget=forms.PasswordInput(), required=False)
    class Meta:
        model=Profile
        fields=['picture','birth_date']



        

        

kijayjay/user/views.py
from .forms import UserForm, ProfileForm, ProfileUpdateForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.shortcuts import redirect
from django.shortcuts import render
from django.views import generic
from django.utils import timezone
from postgresql_db.models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import Group, User
from django.contrib.auth.forms import AuthenticationForm

#Sign up authentication method
def signup(request):
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit = False)
            profile.user_id = user.id
            username = user_form.cleaned_data.get('username')
            password = user_form.cleaned_data.get('password')
            #user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('items:index')
        else:
            messages.error(request, 'Please correct the error below.')
        return render(request, 'user/signup.html', {'user_form': user_form,'profile_form': profile_form})

def login_view(request):
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('items:index')
        else:
            return render(request, 'user/login.html', {'form': form}) 

#Update profile method
@login_required
def update_profile(request, pk):
    user = Profile.objects.filter(user_id=request.user.id).get()
    if request.method == 'POST':
        p_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
       
        if p_form.is_valid():
            p_form.picture = request.user.profile.picture
            p_form.save()
            user.username = request.user.username
            user.email = request.user.email
            
            user.save()
            messages.success(request,'Your Profile has been updated!')
            return redirect('items:index')
    else:
       # initial_p = {'picture': request.user.profile.picture,'username': request.user.username}
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context={'p_form': p_form, 'title':'Update Profile'}
    return render(request, 'user/profile_update.html',context )

class ProfileView(LoginRequiredMixin, generic.DetailView):
    template_name = 'user/profile.html'
    model = Profile
    fields = ['birth_date','money_available', 'picture']
    #permission_required = 'items.view_customer'

kijayjay/user/templates/user/login.html
{% extends 'items/base.html' %}

{% block content %}
<h2>Access all content in Kijayjay today!</h2>
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
    {{ field.label_tag}} <br>
    {{ field }}
    {% if field.help_text%}
    <small style="color: grey">{{ field.help_text }}</small>
    {% endif %}
    {% for error in field.errors %}
     <p style="color: red">{{ error }}</p>
    {% endfor %}
    </p>
    {% endfor%}
    <button type="submit">Log In</button>
</form>
<p>Don't have an account? Join Kijayjay here: <a href="{% url 'user:signup' %}">Register</a></p>
{% endblock %}

kijayjay/user/templates/user/logout.html
{% extends 'items/base.html' %}

{% block content %}
<section class="">
<h3> You are logged out</h3>
    <p>Login again? <a href = "{% url 'login' %}">Login again </a></p>
    <p>No account? <a href = "{% url 'user:signup' %}">register</a></p>
</section>
 {% endblock content %}

kijayjay/user/templates/user/password_update.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'items/style_index.css' %}">
<div class = "header"> <h1>Kijayjay</h1></div>

<ul class = "menu_items">
  <li class="item"><a class="mylink" href="{% url 'items:index' %}">Home</a></li>
  <li class="item"><a class="mylink" href="{% url 'items:sell_item' %}">Sell</a></li>
  {%if user.is_authenticated %}
  <li class="item" style="float:right"><a class="mylink" href="{% url 'logout' %}">Log out</a></li>
  <li class="item" style="float:right">
  <form>
       <input class="item" type="text" style="float:right" placeholder="Search..">
       <button class="item" style="float:right" >Search</button>
   </form>
   </li>
  {%endif%}
</ul> 
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
    {{ field.label_tag}} <br>
    {{ field }}
    {% if field.help_text%}
    <small style="color: grey">{{ field.help_text }}</
    {% endif %}
    {% for error in field.errors %}
     <p style="color: red">{{ error }}</p>
    {% endfor %}
    </p>
    {% endfor%}
    <button type="submit">Post</button>
</form>

kijayjay/user/templates/user/profile.html
{% extends 'items/base.html' %}

{% block content %}
<section id='profile'>
        <h3><b>Welcome, {{ object.user.username }}</b></h3>
    
        <h3> Account Information:</h3>
        {%if object.user.first_name is None %}
        <h4><b>Full name:</b> N/A </h4>
        {% else %}
        <h4><b>Full name:</b> {{ object.user.first_name }} {{ object.user.last_name }} </h4>
        {%endif%}
        {%if object.birth_date is None %}
        <h4><b>Birth date:</b> N/A </h4>
        {% else %}
          <h4><b>Birth date:</b>{{ object.birth_date }}</h4>
        {%endif%}
        <h4><b>Money available:</b> {{ object.money_available }}</h4>
      </section>
<a class="mylink" href="{% url 'user:update_profile' user.id %}">Update profile</a>
{% endblock content %}

kijayjay/user/templates/user/profile_update.html
{% extends 'items/base.html' %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<form method='POST' enctype="multipart/form-data">
    {%csrf_token%}
    {% for field in p_form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: black">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: white">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}

    <button type='submit'>Update</button>
</form>
{% endblock content %}

kijayjay/user/templates/user/signup.html
{% extends 'items/base.html' %}

{% block content %}
<h2>Sign up Form</h2>
<form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Sign up</button>
</form>
{% endblock content %}